# Generated by Django 5.0.1 on 2024-01-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_image_url_alter_comment_name_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.CharField(max_length=250, verbose_name='image_url'),
        ),
    ]
